### ISSUE TITLE
doesn't find package with empty descriptions

### ISSUE THREAD

**Issue by FloLey** [shidenko97/pypisearch#8]
it seems results with an empty description are discarded by `pypisearch` but not by the search on the pypi website.
as example searching for `inmanta-module` returns a lot of results on the website, but only 3 using `pypisearch`
It would be great to be able to have a way to look for those packages as well (maybe not by default, but with an extra flag or something)

**Comment by shidenko97** [comment]
> it seems results with an empty description are discarded by `pypisearch` but not by the search on the pypi website.
> as example searching for `inmanta-module` returns a lot of results on the website, but only 3 using `pypisearch`
> It would be great to be able to have a way to look for those packages as well (maybe not by default, but with an extra flag or something)

Hi! Thanks for your issue, this bug currently fixed in version 1.3.3
